version: "3.8"

services:
  # Backend service
  backend:
    build: ./server
    container_name: barcodesys-backend
    ports:
      - "3004:3003"
    volumes:
      - ./server/database:/app/database
      - ./server/backups:/app/backups
      - ./data:/app/data
      - ./server/scripts:/app/scripts:ro
      - ./server/jobs:/app/jobs:ro
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_PATH=/app/database/inventory.db
      - JWT_SECRET=your_jwt_secret_key_here
      - TZ=Asia/Shanghai
      - SNAPSHOT_ENABLED=true
      - SNAPSHOT_SCHEDULE=0 2 1 * *
    networks:
      - barcodesys-network
    restart: no
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://localhost:3003/api/products && wget --quiet --tries=1 --spider http://localhost:3003/api/snapshots/stats"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend service
  frontend:
    build: ./client
    container_name: barcodesys-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/api
    networks:
      - barcodesys-network
    restart: no
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  barcodesys-network:
    driver: bridge

volumes:
  barcodesys-data:
    driver: local
